apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbeit-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arbeit-backend
  template:
    metadata:
      labels:
        app: arbeit-backend
    spec:
      containers:
        - name: arbeit-backend
          image: yaswanthkalluri/arbeit-backend:temp
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret