apiVersion: v1
kind: Service
metadata:
  name: arbeit-backend-service
spec:
  type: NodePort
  selector:
    app: arbeit-backend
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
