apiVersion: v1
kind: Service
metadata:
  name: skillhive-backend-service
spec:
  selector:
    app: skillhive-backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP