apiVersion: v1
kind: Service
metadata:
  name: skillhive-frontend-service
spec:
  type: NodePort
  selector:
    app: skillhive-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
