apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillhive-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillhive-frontend
  template:
    metadata:
      labels:
        app: skillhive-frontend
    spec:
      containers:
        - name: skillhive-frontend
          image: yaswanthkalluri/skillhive-frontend:latest
          ports:  
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config