apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbeit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arbeit-frontend
  template:
    metadata:
      labels:
        app: arbeit-frontend
    spec:
      containers:
        - name: arbeit-frontend
          image: yaswanthkalluri/arbeit-frontend:temp
          ports:  
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config